spring:
  datasource:
    url: ${USER_DB_URL}
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}
    driverClassName: org.h2.Driver

  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/changelog-master.yml
    default-schema: public